FROM node:25.3.0 as build-stage

WORKDIR /app
COPY ./docs/starlight/package*.json /app/
RUN npm install -g npm@11.7.0
RUN npm install
COPY ./docs/starlight /app/
COPY ./nginx.conf /nginx.conf
COPY ./default.conf /default.conf
RUN npm run build

FROM nginx:1.23

COPY --from=build-stage /app/dist /usr/share/nginx/html/docs
COPY --from=build-stage /default.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /nginx.conf /etc/nginx/nginx.conf
