import { useEffect, useState } from 'react';
import {
  ArrowDownTrayIcon,
  CodeBracketIcon,
  DocumentTextIcon,
} from '@heroicons/react/24/outline';

import { useRxDb } from '../../app/providers/RxDbProvider';
import { useUser } from '../../app/providers/UserProvider';
import { ClinicalDocument } from '../../models/clinical-document/ClinicalDocument.type';
import { AppPage } from '../../shared/components/AppPage';
import { GenericBanner } from '../../shared/components/GenericBanner';
import { safeFormatDate } from '../../shared/utils/dateFormatters';
import { getFhirResource } from '../../shared/utils/fhirResource';
import { firstText } from '../../shared/utils/fhirText';

interface Counts {
  total: number;
  byType: Record<string, number>;
}

function useAllRecords() {
  const db = useRxDb();
  const user = useUser();
  const [docs, setDocs] = useState<ClinicalDocument[]>([]);
  const [status, setStatus] = useState<'loading' | 'success'>('loading');

  useEffect(() => {
    let mounted = true;
    async function load() {
      setStatus('loading');
      const found = await db.clinical_documents
        .find({ selector: { user_id: user.id } })
        .exec();
      if (!mounted) return;
      setDocs(found.map((d) => d.toMutableJSON() as ClinicalDocument));
      setStatus('success');
    }
    load();
    return () => {
      mounted = false;
    };
  }, [db, user.id]);

  return { docs, status };
}

function download(filename: string, content: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function buildBundle(docs: ClinicalDocument[], patientName: string) {
  return {
    resourceType: 'Bundle',
    type: 'collection',
    meta: {
      tag: [
        {
          system: 'https://meremedical.co',
          code: 'mere-export',
          display: `Mere Medical export for ${patientName}`,
        },
      ],
    },
    entry: docs.map((doc) => ({
      fullUrl: doc.metadata?.id,
      resource: getFhirResource(doc),
    })),
  };
}

function esc(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function buildHtmlSummary(
  docs: ClinicalDocument[],
  patientName: string,
): string {
  const groups: { type: string; title: string }[] = [
    { type: 'condition', title: 'Conditions' },
    { type: 'medicationstatement', title: 'Medications' },
    { type: 'allergyintolerance', title: 'Allergies' },
    { type: 'immunization', title: 'Immunizations' },
    { type: 'procedure', title: 'Procedures' },
    { type: 'observation', title: 'Results & vitals' },
  ];
  const today = safeFormatDate('2026-06-09', 'PP', '');
  const sections = groups
    .map(({ type, title }) => {
      const items = docs
        .filter((d) => d.data_record.resource_type === type)
        .map((d) => {
          const r = getFhirResource<Record<string, unknown>>(d);
          const name =
            d.metadata?.display_name ||
            firstText(r['code']) ||
            firstText(r['medicationCodeableConcept']) ||
            firstText(r['vaccineCode']) ||
            'Record';
          const date = d.metadata?.date
            ? safeFormatDate(d.metadata.date, 'PP', '')
            : '';
          return `<tr><td>${esc(name)}</td><td>${esc(date)}</td></tr>`;
        });
      if (items.length === 0) return '';
      return `<h2>${esc(title)} (${items.length})</h2><table><thead><tr><th>Name</th><th>Date</th></tr></thead><tbody>${items.join(
        '',
      )}</tbody></table>`;
    })
    .join('');

  return `<!doctype html><html><head><meta charset="utf-8"><title>Health Summary — ${esc(
    patientName,
  )}</title><style>
    body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#111;max-width:800px;margin:24px auto;padding:0 16px;}
    h1{color:#09384E;margin-bottom:0;} .sub{color:#666;margin-top:4px;}
    h2{color:#09384E;border-bottom:2px solid #e2e8f0;padding-bottom:4px;margin-top:28px;font-size:16px;}
    table{width:100%;border-collapse:collapse;font-size:14px;} th{text-align:left;color:#666;font-weight:600;}
    td,th{padding:6px 8px;border-bottom:1px solid #eee;} .footer{margin-top:32px;color:#999;font-size:12px;}
  </style></head><body>
    <h1>Health Summary</h1>
    <p class="sub">${esc(patientName)} · Generated by Mere Medical on ${esc(today)}</p>
    ${sections || '<p>No records found.</p>'}
    <p class="footer">This document is a patient-generated summary and may be incomplete. Verify with your care team.</p>
  </body></html>`;
}

export function RecordExportTab() {
  const user = useUser();
  const { docs, status } = useAllRecords();

  const counts: Counts = docs.reduce(
    (acc, doc) => {
      acc.total += 1;
      const type = doc.data_record.resource_type;
      acc.byType[type] = (acc.byType[type] || 0) + 1;
      return acc;
    },
    { total: 0, byType: {} } as Counts,
  );

  const patientName =
    [user.first_name, user.last_name].filter(Boolean).join(' ') || 'patient';
  const slug = patientName.toLowerCase().replace(/[^a-z0-9]+/g, '-');

  return (
    <AppPage banner={<GenericBanner text="Export records" />}>
      <div className="h-full overflow-y-auto bg-gray-50">
        <div className="mx-auto grid w-full max-w-3xl gap-4 px-4 py-4 pb-24 sm:px-6 lg:px-8">
          <div className="rounded-md bg-white p-5 shadow-sm ring-1 ring-gray-200">
            <h2 className="text-base font-semibold text-gray-900">
              Download your complete record
            </h2>
            <p className="mt-1 text-sm text-gray-600">
              {status === 'loading'
                ? 'Gathering your records…'
                : `${counts.total} records aggregated across all your connected sources.`}
            </p>

            {status === 'success' && counts.total > 0 && (
              <div className="mt-4 flex flex-wrap gap-1.5">
                {Object.entries(counts.byType)
                  .sort((a, b) => b[1] - a[1])
                  .map(([type, count]) => (
                    <span
                      key={type}
                      className="inline-flex items-center rounded bg-gray-100 px-2 py-0.5 text-xs text-gray-600"
                    >
                      {type} · {count}
                    </span>
                  ))}
              </div>
            )}

            <div className="mt-5 grid gap-3 sm:grid-cols-2">
              <ExportButton
                icon={DocumentTextIcon}
                title="Health summary"
                subtitle="Printable HTML document"
                disabled={status !== 'success' || counts.total === 0}
                onClick={() =>
                  download(
                    `mere-health-summary-${slug}.html`,
                    buildHtmlSummary(docs, patientName),
                    'text/html',
                  )
                }
              />
              <ExportButton
                icon={CodeBracketIcon}
                title="FHIR Bundle"
                subtitle="Standards-based JSON (R4)"
                disabled={status !== 'success' || counts.total === 0}
                onClick={() =>
                  download(
                    `mere-fhir-bundle-${slug}.json`,
                    JSON.stringify(buildBundle(docs, patientName), null, 2),
                    'application/fhir+json',
                  )
                }
              />
            </div>
          </div>

          <p className="text-xs text-gray-400">
            Exports are generated locally on your device — nothing is uploaded.
            The FHIR Bundle can be imported into other health apps; the health
            summary is a portable, human-readable copy.
          </p>
        </div>
      </div>
    </AppPage>
  );
}

function ExportButton({
  icon: Icon,
  title,
  subtitle,
  onClick,
  disabled,
}: {
  icon: typeof DocumentTextIcon;
  title: string;
  subtitle: string;
  onClick: () => void;
  disabled?: boolean;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled}
      className="flex items-center gap-3 rounded-md border border-gray-200 bg-white p-3 text-left shadow-sm transition hover:border-primary-300 hover:bg-primary-50 disabled:cursor-not-allowed disabled:opacity-50"
    >
      <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-md bg-primary-50 text-primary-700">
        <Icon className="h-5 w-5" />
      </span>
      <span className="min-w-0">
        <span className="block text-sm font-semibold text-gray-900">
          {title}
        </span>
        <span className="block text-xs text-gray-500">{subtitle}</span>
      </span>
      <ArrowDownTrayIcon className="ml-auto h-5 w-5 shrink-0 text-gray-400" />
    </button>
  );
}
