import { createId, TerminologyEntry, TerminologyPack } from '@mere/domain';

const packId = 'term_pack_canada_starter_v1';
const createdAt = 0;
const updatedAt = 0;

export const canadaStarterPack: TerminologyPack = {
  id: packId,
  createdAt,
  updatedAt,
  profile: 'canada',
  name: 'Canada starter terminology',
  source: 'Mere starter pack',
  sourceUrl: 'app://starter-terminology/canada',
  sourceVersion: '2026.05-starter',
  license:
    'Starter/demo subset. Use official licensed/imported packs for production terminology coverage.',
  languageCoverage: ['en', 'fr'],
  importedAt: createdAt,
  bundled: true,
};

function entry(
  id: string,
  input: Omit<
    TerminologyEntry,
    'id' | 'createdAt' | 'updatedAt' | 'packId' | 'profile' | 'sourceVersion'
  >,
): TerminologyEntry {
  return {
    id,
    createdAt,
    updatedAt,
    packId,
    profile: 'canada',
    sourceVersion: canadaStarterPack.sourceVersion,
    ...input,
  };
}

export const canadaStarterEntries: TerminologyEntry[] = [
  entry('term_ca_vital_bp_panel', {
    domain: 'vital',
    system: 'http://loinc.org',
    code: '85354-9',
    displayEn: 'Blood pressure',
    displayFr: 'Pression artérielle',
    aliasesEn: ['bp'],
    aliasesFr: ['tension artérielle'],
    units: ['mmHg', 'kPa'],
    defaultUnit: 'mmHg',
    source: 'LOINC / UCUM starter',
    license: canadaStarterPack.license,
    active: true,
  }),
  entry('term_ca_vital_hr', {
    domain: 'vital',
    system: 'http://loinc.org',
    code: '8867-4',
    displayEn: 'Heart rate',
    displayFr: 'Fréquence cardiaque',
    aliasesEn: ['pulse'],
    aliasesFr: ['pouls'],
    units: ['/min', 'bpm'],
    defaultUnit: 'bpm',
    source: 'LOINC / UCUM starter',
    license: canadaStarterPack.license,
    active: true,
  }),
  entry('term_ca_vital_temp', {
    domain: 'vital',
    system: 'http://loinc.org',
    code: '8310-5',
    displayEn: 'Body temperature',
    displayFr: 'Température corporelle',
    aliasesEn: ['temperature'],
    aliasesFr: ['température'],
    units: ['Cel', '[degF]'],
    defaultUnit: 'Cel',
    source: 'LOINC / UCUM starter',
    license: canadaStarterPack.license,
    active: true,
  }),
  entry('term_ca_lab_glucose', {
    domain: 'lab',
    system: 'http://loinc.org',
    code: '2345-7',
    displayEn: 'Glucose',
    displayFr: 'Glucose',
    aliasesEn: ['blood glucose'],
    aliasesFr: ['glycémie'],
    units: ['mmol/L', 'mg/dL'],
    defaultUnit: 'mmol/L',
    source: 'LOINC / UCUM starter',
    license: canadaStarterPack.license,
    active: true,
  }),
  entry('term_ca_lab_a1c', {
    domain: 'lab',
    system: 'http://loinc.org',
    code: '4548-4',
    displayEn: 'Hemoglobin A1c',
    displayFr: 'Hémoglobine A1c',
    aliasesEn: ['a1c', 'hba1c'],
    aliasesFr: ['hba1c'],
    units: ['%', 'mmol/mol'],
    defaultUnit: '%',
    source: 'LOINC / UCUM starter',
    license: canadaStarterPack.license,
    active: true,
  }),
  entry('term_ca_med_acetaminophen', {
    domain: 'medication',
    system: 'http://terminology.hl7.org/CodeSystem/hc-CCDD',
    code: 'starter-acetaminophen',
    displayEn: 'Acetaminophen',
    displayFr: 'Acétaminophène',
    aliasesEn: ['paracetamol', 'tylenol'],
    aliasesFr: ['paracétamol'],
    source: 'CCDD-compatible starter',
    license: canadaStarterPack.license,
    active: true,
  }),
  entry('term_ca_immunization_influenza', {
    domain: 'immunization',
    system: 'https://cvc.canimmunize.ca',
    code: 'starter-influenza',
    displayEn: 'Influenza vaccine',
    displayFr: 'Vaccin contre la grippe',
    aliasesEn: ['flu vaccine'],
    aliasesFr: ['vaccin antigrippal'],
    source: 'Canadian Vaccine Catalogue-compatible starter',
    license: canadaStarterPack.license,
    active: true,
  }),
  entry('term_ca_condition_hypertension', {
    domain: 'condition',
    system: 'app://mere/terminology/common-condition',
    code: 'hypertension',
    displayEn: 'Hypertension',
    displayFr: 'Hypertension',
    aliasesEn: ['high blood pressure'],
    aliasesFr: ['haute pression'],
    source: 'Mere common terms starter',
    license: canadaStarterPack.license,
    active: true,
  }),
  entry('term_ca_allergy_penicillin', {
    domain: 'allergy',
    system: 'app://mere/terminology/common-allergy',
    code: 'penicillin-allergy',
    displayEn: 'Penicillin allergy',
    displayFr: 'Allergie à la pénicilline',
    source: 'Mere common terms starter',
    license: canadaStarterPack.license,
    active: true,
  }),
  entry('term_ca_procedure_appendectomy', {
    domain: 'procedure',
    system: 'app://mere/terminology/common-procedure',
    code: 'appendectomy',
    displayEn: 'Appendectomy',
    displayFr: 'Appendicectomie',
    source: 'Mere common terms starter',
    license: canadaStarterPack.license,
    active: true,
  }),
  entry('term_ca_encounter_ambulatory', {
    domain: 'encounter',
    system: 'http://terminology.hl7.org/CodeSystem/v3-ActCode',
    code: 'AMB',
    displayEn: 'Ambulatory visit',
    displayFr: 'Visite ambulatoire',
    aliasesEn: ['office visit'],
    aliasesFr: ['visite au cabinet'],
    source: 'HL7 ActCode starter',
    license: 'HL7/FHIR terminology starter subset',
    active: true,
  }),
];

export function createTerminologyEntryId(prefix = 'term'): string {
  return createId(prefix);
}
