import { TDateISO } from './Date';

export type ClinicalDocumentResourceType =
  | 'allergyintolerance'
  | 'appointment'
  | 'careplan'
  | 'careteam'
  | 'condition'
  | 'consent'
  | 'contract'
  | 'coverage'
  | 'device'
  | 'diagnosticreport'
  | 'documentreference'
  | 'documentreference_attachment'
  | 'encounter'
  | 'familymemberhistory'
  | 'goal'
  | 'immunization'
  | 'insuranceplan'
  | 'imagingstudy'
  | 'location'
  | 'media'
  | 'medication'
  | 'medicationadministration'
  | 'medicationdispense'
  | 'medicationorder'
  | 'medicationrequest'
  | 'medicationstatement'
  | 'nutritionorder'
  | 'observation'
  | 'organization'
  | 'patient'
  | 'person'
  | 'practitioner'
  | 'practitionerrole'
  | 'procedure'
  | 'provenance'
  | 'questionnaire'
  | 'questionnaireresponse'
  | 'relatedperson'
  | 'schedule'
  | 'servicerequest'
  | 'slot'
  | 'specimen'
  | 'visionprescription';

export interface ClinicalDocument<T = unknown> {
  id: string; // This gets autogenerated, see ClinicalDocument.schema.ts
  connection_record_id: string;
  user_id: string;
  data_record: {
    raw: T;
    format: 'FHIR.DSTU2' | 'FHIR.R4';
    content_type: 'application/json' | 'application/xml' | string;
    resource_type: ClinicalDocumentResourceType;
    version_history: T[];
  };
  attachment_ids?: string[];
  metadata?: {
    id?: string;
    date?: TDateISO | string;
    display_name?: string;
    loinc_coding?: string[];
    terminology_profile?: string;
    terminology_source?: string;
    terminology_source_version?: string;
    manual_uncoded?: boolean;
    manual_specialty?: string;
    manual_subtype?: string;
    manual_specialty_details?: unknown;
    manual_imaging_details?: {
      modality?: string;
      bodySite?: string;
      laterality?: string;
      studyType?: string;
      accessionId?: string;
      studyId?: string;
    };
  };
}

export type CreateClinicalDocument<T> = Omit<ClinicalDocument<T>, 'id'>;

export interface MergeClinicalDocument<T> extends ClinicalDocument {
  data_items?: T[];
}
