export enum Routes {
  Timeline = '/timeline',
  Records = '/records',
  Labs = '/records/labs',
  LabDetail = '/records/labs/:labKey',
  Imaging = '/records/imaging',
  Dental = '/records/dental',
  AddRecord = '/records/new',
  EditRecord = '/records/:recordId/edit',
  AddConnection = '/connections',
  Summary = '/summary',
  MereAIAssistant = '/assistant',
  Settings = '/settings',
  OnPatientCallback = '/onpatient/callback',
  EpicCallback = '/epic/callback',
  CernerCallback = '/cerner/callback',
  VeradigmCallback = '/veradigm/callback',
  VACallback = '/va/callback',
  HealowCallback = '/healow/callback',
}
