export enum Routes {
  Timeline = '/timeline',
  Labs = '/labs',
  LabDetail = '/labs/:labKey',
  Imaging = '/imaging',
  AddRecord = '/records/new',
  EditRecord = '/records/:recordId/edit',
  AddConnection = '/connections',
  Summary = '/summary',
  MereAIAssistant = '/assistant',
  Settings = '/settings',
  OnPatientCallback = '/onpatient/callback',
  EpicCallback = '/epic/callback',
  CernerCallback = '/cerner/callback',
  VeradigmCallback = '/veradigm/callback',
  VACallback = '/va/callback',
  HealowCallback = '/healow/callback',
}
